### ISSUE TITLE
Supporting viewparams

### ISSUE THREAD

**Issue by vittrup88** [emplexed/gs-mvt#14]
I have been looking in the code and can’t figure if this extension support the wms viewparams?

It is not mentioned in the code so does it inherit from wms?

I have successfully used this feature with the community module for vector tiles as mvt but I really like the idea implemented here to control the generalization and small geometries.
I have a smaller problem with the community module where some features will disappear. It might be solved by setting the size of tile grid from 256x256 to a higher resolution, but still here it is possible to make a precise configuration.

**Comment by emplexed** [comment]
yes your right, im also stepping into the problem again and again.  Basically we still use the plugin for similar reasons (generalization control etc.). 

I hope i find time to update the plugin with viewparam support. currently the issue is that we proxy the requests using a slippymap controller (to avoid the need to request over GWC and still get the slippy map format). This controller currently ignores the viewparams.

**Comment by emplexed** [comment]
if its still relevant for you, viewparams are supported in Version 0.3.3. 

Please not, Geoserver 2.13 is currently the max supported version, there are JTS Upgrade issues to get compatible with 2.14 onwards. I will start a new branch for that issue and keep the 0.3.X as maintenance for branch for older Geoservers.
