### ISSUE TITLE
caching

### ISSUE THREAD

**Issue by stvno** [emplexed/gs-mvt#3]
Does the plugin cache the vector tiles and if so, is it possible to seed the cache?

**Comment by stefan0722** [comment]
You can use an external Geowebcache 1.8.0 to seed the vector tiles. The build-in GWC is not working because of lack of UI support. You get an error reponse code if you try to request tiles from the GWC which contain no data. I already reported that to the GWC team, but with OpenLayers this does not have any effect on usability

But the Geoserver Team has also developed an VectorTiles integration in version 2.8.0. I didn't test it but maybe it is also worth to have a look at it.

**Comment by stvno** [comment]
Thanks for the pointer to the vectortiles plugin. I'm investigating it now, it doesn't produce 'broken' tiles, which is good, but for some reason I can't get the buffer working, which is bad ;)

**Comment by ghost** [comment]
Apologies for going slightly off-topic, but I can't find any integrated vector tiles in Geoserver 2.8. What am I missing?

Edit: Ignore me... I was missing the WFS GeoJSON format.
